package communication;

public enum OpCode {
	STORE_FILES, LIST_FILES, REMOVE_FILES, USERS, TRUST_USERS, 
	UNTRUST_USERS, DOWNLOAD_FILE, SEND_MSG, SHOW_MSG, 
	END_CONNECTION,
	OP_ERROR, OP_SUCCESSFUL;
}
